routes/admin.php
<?php
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    //Marcas
    Route::group(['prefix' => 'marcas'], function () {
        Route::get('/', 'Admin\MarcasController@listado')->name('admin.marcas.listado');
        Route::group(['prefix' => 'nueva'], function () {
            Route::get('/', 'Admin\MarcasController@nueva')->name('admin.marcas.nueva');
            Route::post('guardar', 'Admin\MarcasController@guardar')->name('admin.marcas.nueva.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\MarcasController@editar')->name('admin.marcas.editar');
            Route::put('actualizar', 'Admin\MarcasController@actualizar')->name('admin.marcas.editar.actualizar');
        });
        Route::group(['prefix' => 'cargue-masivo'], function () {
            Route::get('/', 'Admin\MarcasController@cargueMasivo')->name('admin.marcas.cargue-masivo');
            Route::post('cargar', 'Admin\MarcasController@cargar')->name('admin.marcas.cargue-masivo.cargar');
        });

    });

    //Categorías
    Route::group(['prefix' => 'categorias'], function () {
        Route::get('/', 'Admin\CategoriasController@listado')->name('admin.categorias.listado');
        Route::group(['prefix' => 'nueva'], function () {
            Route::get('/', 'Admin\CategoriasController@nueva')->name('admin.categorias.nueva');
            Route::post('guardar', 'Admin\CategoriasController@guardar')->name('admin.categorias.nueva.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\CategoriasController@editar')->name('admin.categorias.editar');
            Route::put('actualizar', 'Admin\CategoriasController@actualizar')->name('admin.categorias.editar.actualizar');
        });
        Route::group(['prefix' => 'cargue-masivo'], function () {
            Route::get('/', 'Admin\CategoriasController@cargueMasivo')->name('admin.categorias.cargue-masivo');
            Route::post('cargar', 'Admin\CategoriasController@cargar')->name('admin.categorias.cargue-masivo.cargar');
        });
    });

    //Productos
    Route::group(['prefix' => 'productos'], function () {
        Route::get('/', 'Admin\ProductosController@listado')->name('admin.productos.listado');
        Route::group(['prefix' => 'nuevo'], function () {
            Route::get('/', 'Admin\ProductosController@nuevo')->name('admin.productos.nuevo');
            Route::post('guardar', 'Admin\ProductosController@guardar')->name('admin.productos.nuevo.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\ProductosController@editar')->name('admin.productos.editar');
            Route::put('actualizar', 'Admin\ProductosController@actualizar')->name('admin.productos.editar.actualizar');
        });
        Route::group(['prefix' => 'cargue-masivo'], function () {
            Route::get('/', 'Admin\ProductosController@cargueMasivo')->name('admin.productos.cargue-masivo');
            Route::post('cargar', 'Admin\ProductosController@cargar')->name('admin.productos.cargue-masivo.cargar');
        });
    });

    //Clientes
    Route::group(['prefix' => 'clientes'], function () {
        Route::get('/', 'Admin\ClientesController@listado')->name('admin.clientes.listado');
        Route::group(['prefix' => 'nuevo'], function () {
            Route::get('/', 'Admin\ClientesController@nuevo')->name('admin.clientes.nuevo');
            Route::post('guardar', 'Admin\ClientesController@guardar')->name('admin.clientes.nuevo.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\ClientesController@editar')->name('admin.clientes.editar');
            Route::put('actualizar', 'Admin\ClientesController@actualizar')->name('admin.clientes.editar.actualizar');
        });
        
        Route::get('buscar', 'ClientesController@buscar');
    });

    //Usuarios
    Route::group(['prefix' => 'users'], function () {
        Route::get('/', 'Admin\UsersController@listado')->name('admin.users.listado');
        Route::group(['prefix' => 'nuevo'], function () {
            Route::get('/', 'Admin\UsersController@nuevo')->name('admin.users.nuevo');
            Route::post('guardar', 'Admin\UsersController@guardar')->name('admin.users.nuevo.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\UsersController@editar')->name('admin.users.editar');
            Route::put('actualizar', 'Admin\UsersController@actualizar')->name('admin.users.editar.actualizar');
        });
    });

    //Promociones
    Route::group(['prefix' => 'promociones'], function () {
        Route::get('/', 'Admin\PromocionesController@listado')->name('admin.promociones.listado');
        Route::group(['prefix' => 'nueva'], function () {
            Route::get('/', 'Admin\PromocionesController@nueva')->name('admin.promociones.nueva');
            Route::post('guardar', 'Admin\PromocionesController@guardar')->name('admin.promociones.nueva.guardar');
        });
        Route::group(['prefix' => 'editar/{id}'], function () {
            Route::get('/', 'Admin\PromocionesController@editar')->name('admin.promociones.editar');
            Route::put('actualizar', 'Admin\PromocionesController@actualizar')->name('admin.promociones.editar.actualizar');
        });
        Route::group(['prefix' => 'cargue-masivo'], function () {
            Route::get('/', 'Admin\PromocionesController@cargueMasivo')->name('admin.promociones.cargue-masivo');
            Route::post('cargar', 'Admin\PromocionesController@cargar')->name('admin.promociones.cargue-masivo.cargar');
        });
        Route::group(['prefix' => '{id}/clientes'], function () {
            Route::get('/', 'Admin\PromocionesController@clientes')->name('admin.promociones.clientes');
            Route::post('guardar', 'Admin\PromocionesController@guardarClientes')->name('admin.promociones.clientes.guardar');
            Route::delete('eliminar', 'Admin\PromocionesController@eliminarCliente')->name('admin.promociones.clientes.eliminar');
        });
        Route::group(['prefix' => '{id}/mailing'], function () {
            Route::get('/', 'Admin\PromocionesController@mailing')->name('admin.promociones.mailing');
            Route::post('guardar', 'Admin\PromocionesController@guardarMailing')->name('admin.promociones.mailing.guardar');
            Route::delete('{mailing_id}/eliminar', 'Admin\PromocionesController@eliminarMailing')->name('admin.promociones.mailing.eliminar');
        });
    });
    
    //Reportes
    Route::group(['prefix' => 'pedidos'], function () {
        Route::get('/', 'Admin\PedidosController@index')->name('admin.pedidos.listado');
        Route::get('detalle/{}', 'Admin\PedidosController@detalle')->name('admin.pedidos.detalle');
        Route::get('nuevo', 'Admin\PedidosController@nuevo')->name('admin.pedidos.nuevo');
        Route::post('guardar', 'Admin\PedidosController@guardar')->name('admin.pedidos.guardar');
    });
});

Route::group(['prefix' => 'users/crear-contraseña'], function () {
    Route::get('/', 'Admin\UsersController@crearContrasena')->name('admin.users.crear-contrasena');
    Route::post('guardar-contrasena', 'Admin\UsersController@guardarContrasena')->name('admin.users.crear-contrasena.guardar-contrasena');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('tienda.index');
});


//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Cliente extends Model
{
    const CREATED_AT = 'fecha_creacion';
    const UPDATED_AT = 'fecha_modificacion';
    
    protected $fillable = [
        'name', 'email',
    ];
    
    protected $dates = [
        'fecha_creacion',
        'fecha_modificacion',
    ];
    
    /**
     * Obtiene antigüedad del cliente.
     *
     * @author María Paulina Ramírez Vásquez    <maria.paulina.r.v@gmail.com>
     *
     * @return string
    */
    public function getAntiguedadAttribute()
    {
        $dias = $this->fecha_creacion->diffInDays(Carbon::now());
        $res = ($dias == 1) ? ' día' : ' días';
        
        if($dias > 7) {
            $res = $this->fecha_creacion->diffInWeeks(Carbon::now());
            $res .= ($res == 1) ? ' semana' : ' semanas';
        }
        
        if($dias > 30) {
            $res = $this->fecha_creacion->diffInMonths(Carbon::now());
            $res .= ($res == 1) ? ' mes' : ' meses';
        }
        
        if($dias > 365) {
            $res = $this->fecha_creacion->diffInYears(Carbon::now());
            $res .= ($res == 1) ? ' año' : ' años';
        }
        
        return $res;
    }
}

resources/views/admin/promociones/acciones-mailing.blade.php
<form method="post" action="{{ route('admin.promociones.mailing.eliminar', [$mailing->promocion_id, $mailing->id]) }}" onsubmit="return confirm('¿Confirma que desea eliminar esta campaña de mailing? Tenga en cuenta que al eliminarla suspenderá los envíos de esta campaña que estén en curso.');">
    {!! csrf_field() !!}
    {!! method_field('DELETE') !!}
    <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Eliminar esta campaña de mailing"><i class="fa fa-trash"></i></button>
</form>

resources/views/admin/promociones/acciones.blade.php
<a href="{{ route('admin.promociones.editar', [$promocion->id]) }}" data-toggle="tooltip" data-placement="top" title="Editar este registro"><i class="fa fa-pencil"></i></a>
<a href="{{ route('admin.promociones.clientes', [$promocion->id]) }}" data-toggle="tooltip" data-placement="top" title="Asignar clientes"><i class="fa fa-user-circle-o"></i></a>
<a href="{{ route('admin.promociones.mailing', [$promocion->id]) }}" data-toggle="tooltip" data-placement="top" title="Mailing"><i class="fa fa-envelope-o"></i></a>

resources/views/admin/promociones/campos.blade.php
{!! csrf_field() !!}
<div class="row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label>Producto en promoción</label>
        <select name="producto_id" class="form-control select2" required>
            @if($promocion)
                @foreach($productos as $producto)
                    @php
                        $selected = ($producto->id == $promocion->producto_id) ? ' selected' : '';
                    @endphp
                    <option value="{{ $producto->id }}"{{ $selected }}>{{ $producto->descripcion }}</option>
                @endforeach
            @else
                @foreach($productos as $producto)
                    <option value="{{ $producto->id }}">{{ $producto->descripcion }}</option>
                @endforeach
            @endif
        </select>
    </div>
</div>
<div class="row">
    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
        <label>Código</label>
        <input type="text" name="codigo" id="codigo" class="form-control" placeholder="Código de la promocion" maxlength="20" value="{{ ($promocion) ? $promocion->codigo : '' }}">
    </div>
    <div class="form-group col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <label>Descripción</label>
        <input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Descripción de la promocion" maxlength="255" value="{{ ($promocion) ? $promocion->descripcion : '' }}" required>
    </div>
</div>
<div class="row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label>Descripción larga</label>
        <textarea name="descripcion_larga" id="descripcion_larga" class="form-control" placeholder="Descripción larga de la promocion" rows="5" style="height: 150px;">{{ ($promocion) ? $promocion->descripcion_larga : '' }}</textarea>
    </div>
</div>
<div class="row">
    <div class="form-group col-4">
        <label>Desde</label>
        <input type="text" name="fecha_hora_inicio" class="form-control fecha-hora mask-fecha-hora" placeholder="" value="{{ ($promocion) ? $promocion->fecha_hora_inicio : '' }}" required>
    </div>
    <div class="form-group col-4">
        <label>Hasta</label>
        <input type="text" name="fecha_hora_fin" class="form-control fecha-hora mask-fecha-hora" placeholder="" value="{{ ($promocion) ? $promocion->fecha_hora_fin : '' }}" required>
    </div>
</div>
<div class="row">
    <div class="form-group col-3">
        <label>Precio de venta</label>
        <input type="text" name="precio_venta" class="form-control" placeholder="" value="{{ ($promocion) ? $promocion->precio_venta : '' }}" required>
    </div>
    <div class="form-group col-3">
        <label>Cantidad dispuesta</label>
        <input type="text" name="cantidad_dispuesta" class="form-control" placeholder="" value="{{ ($promocion) ? $promocion->cantidad_dispuesta : '' }}">
    </div>
    <div class="form-group col-3">
        <label>Cantidad mínima compra</label>
        <input type="text" name="cantidad_min" class="form-control" placeholder="" value="{{ ($promocion) ? $promocion->cantidad_min : '' }}">
    </div>
    <div class="form-group col-3">
        <label>Cantidad máxima compra</label>
        <input type="text" name="cantidad_max" class="form-control" placeholder="" value="{{ ($promocion) ? $promocion->cantidad_max : '' }}">
    </div>
</div>
<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
<button type="button" class="btn btn-default" id="cancelar"><i class="fa fa-close"></i> Cancelar</button>

resources/views/admin/promociones/cargue-masivo.blade.php
@extends('admin.layout.master')

@section('titulo')
Cargue masivo de promociones
@endsection

@section('contenido')
<div class="row">
    <div class="col-12 alert alert-info">
        <h4 class="text-center"><i class="fa fa-info-circle"></i> Cargue un archivo .xls, .xlsx o .csv</h4>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <a href="{{ asset('docs/admin/promociones.xlsx') }}" target="_blank" class="btn btn-secondary pull-right" role="button"><i class="fa fa-file-excel-o"></i> Descargar archivo modelo</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="basic-form">
                    <form action="{{ route('admin.promociones.cargue-masivo.cargar') }}" method="post" enctype="multipart/form-data" onsubmit="mostrarLoading();">
                        {!! csrf_field() !!}
                        <div class="row">
                            <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="file" name="archivo" id="archivo" class="dropify" data-allowed-file-extensions="xls xlsx csv" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-4">
                                <label>Desde</label>
                                <input type="text" name="fecha_hora_inicio" class="form-control fecha-hora mask-fecha-hora" placeholder="" value="">
                            </div>
                            <div class="form-group col-4">
                                <label>Hasta</label>
                                <input type="text" name="fecha_hora_fin" class="form-control fecha-hora mask-fecha-hora" placeholder="" value="">
                            </div>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-primary"><i class="fa fa-play"></i> Empezar la carga</button>
                        <button type="button" class="btn btn-default" id="cancelar"><i class="fa fa-close"></i> Cancelar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready(function () {
    $("#cancelar").on("click", function (e) {
        e.preventDefault();
        location.href = "{{ route('admin.promociones.listado') }}";
    });
});
</script>
@endsection

resources/views/admin/promociones/clientes.blade.php
@extends('admin.layout.master')
@section('css')
<style>
    .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
        background-color: #dee2e694;
        border-color: #dee2e6 #dee2e6 #dee2e6;
    }
    
    .nav-tabs .nav-link:focus, .nav-tabs .nav-link:hover {
        background-color: #dee2e694;
        border-color: #e9ecef #e9ecef #dee2e6;
    }
</style>
@endsection
@section('titulo')
Clientes de la promoción
@endsection

@section('contenido')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link{{ (!request()->has('registrados')) ? ' active' : '' }}" data-toggle="tab" href="#clientes-promocion" role="tab"><h3>Aplicados a la promoción</h3></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link{{ (request()->has('registrados')) ? ' active' : '' }}" data-toggle="tab" href="#segmentacion" role="tab"><h3>Agregar por segmentación de clientes</h3></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#manual" role="tab"><h3>Agregar por selección manual</h3></a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane{{ (!request()->has('registrados')) ? ' active' : '' }}" id="clientes-promocion" role="tabpanel">
                                <div class="row">
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        @if(!$clientes_promocion->isEmpty())
                                        <table class="table table-condensed table-hover" id="table-clientes-promocion">
                                            <thead>
                                                <tr>
                                                    <th>Identificación</th>
                                                    <th>Razón social</th>
                                                    <th>Antigüedad</th>
                                                    <th>Eliminar de la promoción</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($clientes_promocion as $cliente)
                                                <tr>
                                                    <td>{{ $cliente->identificacion }}</td>
                                                    <td>{{ $cliente->razon_social }}</td>
                                                    <td>{{ $cliente->antiguedad }}</td>
                                                    <td>
                                                        <form action="{{ route('admin.promociones.clientes.eliminar', [$promocion->id]) }}" method="post" onsubmit="if(!confirm('¿Confirma que desea eliminar este cliente de la promoción?')) { return false; }">
                                                            {!! csrf_field() !!}
                                                            {!! method_field('DELETE') !!}
                                                            <input type="hidden" name="cliente_id" value="{{ $cliente->id }}">
                                                            <button type="submit" class="btn btn-danger btn-sm" title="Eliminar"><i class="fa fa-trash"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                        @else
                                        <p>&nbsp;</p>
                                        <div class="alert alert-info">
                                            <h3 style="text-align: center;">Esta promoción aplica a todos los clientes</h3>
                                        </div>
                                        @endif
                                    </div>
                                </div>
                                <div class="row">
                                    <div col-lg-12 col-md-12 col-sm-12 col-xs-12>
                                        <button type="button" class="cancelar btn btn-default"><i class="fa fa-arrow-left"></i> Regresar al listado de promociones</button>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane{{ (request()->has('registrados')) ? ' active' : '' }}" id="segmentacion" role="tabpanel">
                                <form action="{{ route('admin.promociones.clientes.guardar', [$promocion->id]) }}" method="post" enctype="multipart/form-data">
                                    {!! csrf_field() !!}
                                    <fieldset>
                                        <legend>Filtrar clientes</legend>
                                        <div class="form-inline">
                                            <div class="form-group">
                                                <label class="filter-col">Registrados</label>
                                                <select class="form-control" id="registrados">
                                                    <option value="todos">Todos</option>
                                                    <option value="no-realizado-compras"{{ (request()->registrados == 'no-realizado-compras') ? ' selected' : '' }}>No han realizado compras</option>
                                                    <option value="nunca-visitado-tienda"{{ (request()->registrados == 'nunca-visitado-tienda') ? ' selected' : '' }}>Nunca han visitado la tienda</option>
                                                    <option value="no-visitan-tienda-mas-3-meses"{{ (request()->registrados == 'no-visitan-tienda-mas-3-meses') ? ' selected' : '' }}>No visitan la tienda hace más de 3 meses</option>
                                                    <option value="no-visitan-tienda-mas-6-meses"{{ (request()->registrados == 'no-visitan-tienda-mas-6-meses') ? ' selected' : '' }}>No visitan la tienda hace más de 6 meses</option>
                                                    <option value="no-visitan-tienda-mas-12-meses"{{ (request()->registrados == 'no-visitan-tienda-mas-12-meses') ? ' selected' : '' }}>No visitan la tienda hace más de 1 año</option>
                                                </select>
                                            </div>
                                        </div>
                                    </fieldset>
                                    <div class="row">
                                        <div class="col-12">
                                            <p>&nbsp;</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <table class="table table-condensed table-hover" id="table-segmentacion">
                                                <thead>
                                                    <tr>
                                                        <th><input type="checkbox" class="form-control" value="" id="checkall" checked></th>
                                                        <th>Identificación</th>
                                                        <th>Razón social</th>
                                                        <th>Antigüedad</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($clientes as $cliente)
                                                    <tr>
                                                        <td><input type="checkbox" class="form-control" name="cliente_id[]" value="{{ $cliente->id }}" checked></td>
                                                        <td>{{ $cliente->identificacion }}</td>
                                                        <td>{{ $cliente->razon_social }}</td>
                                                        <td>{{ $cliente->antiguedad }}</td>
                                                    </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <hr>
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Aplicar</button>
                                    <button type="button" class="cancelar btn btn-default"><i class="fa fa-close"></i> Cancelar</button>
                                </form>
                            </div>
                            <div class="tab-pane" id="manual" role="tabpanel">
                                <form action="{{ route('admin.promociones.clientes.guardar', [$promocion->id]) }}" method="post" enctype="multipart/form-data">
                                    {!! csrf_field() !!}
                                    <div class="row">
                                        <div class="col-12">
                                            <p>&nbsp;</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <label>Escriba parte del nombre o la identificación del (los) cliente(s) y selecciónelo(s)</label>
                                            <select name="cliente_id[]" class="form-control select2" data-width="100%" multiple="">
                                                @foreach($clientes as $cliente)
                                                    <option value="{{ $cliente->id }}">{{ $cliente->identificacion }} - {{ $cliente->razon_social }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <hr>
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Aplicar</button>
                                    <button type="button" class="cancelar btn btn-default"><i class="fa fa-close"></i> Cancelar</button>
                                </form>
                            </div>
                        </div>
                        
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready(function () {
    $(".cancelar").on("click", function (e) {
        e.preventDefault();
        location.href = "{{ route('admin.promociones.listado') }}";
    });
    
    $("#registrados").on("change", function () {
        location.href = "{{ url()->current() }}?registrados=" + $(this).val();
    });
});
</script>
@endsection

resources/views/admin/promociones/editar.blade.php
@extends('admin.layout.master')

@section('titulo')
Editar promoción: {{ $promocion->descripcion }}
@endsection

@section('contenido')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="basic-form">
                    <form action="{{ route('admin.promociones.editar.actualizar', [$promocion->id]) }}" method="post" enctype="multipart/form-data">
                        {!! method_field('PUT') !!}
                        @include('admin.promociones.campos', ['promocion' => $promocion])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready(function () {
    $("#cancelar").on("click", function (e) {
        e.preventDefault();
        location.href = "{{ route('admin.promociones.listado') }}";
    });
});
</script>
@endsection

resources/views/admin/promociones/listado.blade.php
@extends('admin.layout.master')

@section('titulo')
Promociones
@endsection

@section('contenido')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-6">
                        <label for="estado">Filtrar por estado</label>
                        <select name="estado" id="estado" class="form-control">
                            <option value="">Todas las promociones</option>
                            <option value="vigentes">Promociones vigentes</option>
                            <option value="vencidas">Promociones vencidas</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {!! $dataTable->table() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
{!! $dataTable->scripts() !!}
<script type="text/javascript">
$(document).ready(function () {
    $("#dataTableBuilder").on('preXhr.dt', function(e, settings, data) {
        data.estado = $("#estado").val();
    });
    
    $("#estado").on("change", function () {
        window.LaravelDataTables["dataTableBuilder"].draw();
    });
});
</script>
@endsection